#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2016-2017 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import fcntl
import os
import termios

def push(s):
    fd = 0
    for fd in range(0, 3):
        try:
            fcntl.ioctl(fd, termios.TIOCSTI, s[0])
        except IOError:
            continue
        else:
            break
    else:
        fd = os.open('/dev/tty', os.O_RDONLY)
        fcntl.ioctl(fd, termios.TIOCSTI, s[0])
    for ch in s[1:]:
        fcntl.ioctl(fd, termios.TIOCSTI, ch)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('command', metavar='COMMAND')
    ap.add_argument('rest', nargs='*', help=argparse.SUPPRESS)
    options = ap.parse_args()
    cmdline = ' '.join([options.command] + options.rest)
    push(' {cmd}\n'.format(cmd=cmdline))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
